// =============================================================================
// SISTEMA DE EMPRESA — Aurora Roleplay 2026
// sistema_empresa.inc
// =============================================================================

stock Empresa_CarregarTodas()
{
    printf("[EMPRESAS] Sistema de empresas inicializado.");
    return 1;
}

stock Empresa_Salvar(id)
{
    return 1;
}

stock Empresa_VerificarInatividade(id)
{
    return 1;
}

stock Empresa_ProcessarDialog(playerid, dialogid, response, listitem, inputtext[])
{
    return 1;
}