// =============================================================================
// SISTEMA DE ORGANIZAÇÃO — Aurora Roleplay 2026
// sistema_organizacao.inc
// =============================================================================

stock Org_CarregarTodas()
{
    printf("[ORGANIZAÇÕES] Sistema de organizações inicializado.");
    return 1;
}

stock Org_Salvar(id)
{
    return 1;
}

stock Org_ProcessarDialog(playerid, dialogid, response, listitem, inputtext[])
{
    return 1;
}